apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app3
  labels:
    app: web-app3
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app3
  template:
    metadata:
      labels:
        app: web-app3
    spec:
      containers:
      - name: app3
        image: {{ .Values.deployment.image.name }}
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.1"
        env:
          - name: MESSAGE
            value: 'App 3 !'
          - name: PORT
            value: '80'