apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: devops
data:
  nginx.conf: |
    upstream alb
    {
            server app-1-service:80;
            server app-2-service:80;
    }
    server {
        listen 80 default_server;
        server_name _;

        location / {
            return 404;
        }

        location /original {
            proxy_pass http://alb;
        }

        location /v1 {
    		return 307 /original;
    	}

    	location /v2 {
    		return 307 /original;
    	}

        location /v3 {
            proxy_pass http://app-3-service:80;
        }

        location /v4 {
            proxy_pass http://app-4-service:80;
        }
    }

