kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf
  namespace: devops
data:
  default.conf: |
    upstream alb {
        server web-app1:80;
        server web-app2:80;
    }
    server {
        listen 80 default_server;
        server_name _;

        location / {
          return 404;
        }

        location /original {
          proxy_pass http://alb;
        }

        location /v1 {
          return 307 /original;
        }

        location /v2 {
          return 307 /original;
        }

        location /v3 {
          proxy_pass http://web-app3:80;
        }

        location /v4 {
          proxy_pass http://web-app4:80;
        }
    }
