FROM mhart/alpine-node:14 as webpage 

# Working Directory
WORKDIR /app

# Not have permission so need to contain src into that Docker
COPY ./src /app

# # enrontment msg env variable
# ARG message=${msg}
# ENV MESSAGE ${message}

# Install & Build app 
RUN npm install

CMD [ "npm","start" ]


