FROM nginx:latest
# Get the config and add it into Nginx image 
COPY ./conf /

# Executable moving and overwrite nginx.conf default by copy version
RUN cat nginx.conf > /etc/nginx/conf.d/default.conf
RUN mv www.example.com.crt /etc/nginx/
RUN mv www.example.com.key /etc/nginx/