FROM nginx:1.23.3

COPY ./conf /

ARG domain_key
ENV domain_key=${domain_key}

ARG domain_crt
ENV domain_crt=${domain_crt}

RUN mv *.key  /etc/nginx/

RUN mv *.crt  /etc/nginx/
 
RUN mv nginx.conf default.conf.template

RUN envsubst < default.conf.template > /etc/nginx/conf.d/default.conf
