apiVersion: v1
kind: Service
metadata:
  name: app-1-service
  namespace: devops
spec:
  selector:
    app.kubernetes.io/name: app-1
  ports:
    - name: app1
      protocol: TCP
      port: 80
      targetPort: 8001