namespace: devops
deployment: 
  image:
    name: devopsorient.azurecr.io/webpage8001:latest
    resources:
      memory: "256Mi"
      cpu: "0.1"
  containerPort: 80
env:
  name: MESSAGE
  value: 'App 1 !'
  port:
    name: PORT
    value: "80"

service: 
  protocol: TCP
  namespace: devops
  servicePort: 80
  serviceTagetPort: 80
