namespace: devops
deployment: 
  image:
    name: devopsorient.azurecr.io/webpage8003:latest
    resources:
      limits:
        memory: "256Mi"
        cpu: "0.1"
    env:
          - name: MESSAGE
            value: 'App 3 !'
          - name: PORT
            value: '80'
  containerPort: 80
service: 
  protocol: TCP
  namespace: devops
  servicePort: 80
  serviceTagetPort: 80