apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.spec.ingressClassName }}
  rules:
    - http:
        paths:
        - pathType: {{ .Values.spec.rules.routeType }}
          path: '{{ .Values.spec.rules.path }}'
          backend:
            service:
              name: {{ .Values.spec.service.name }}
              port:
                number: {{ .Values.spec.service.port }}
