apiVersion: v1
kind: Service
metadata:
  name: web-app1
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: web-app1
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: app1
    protocol: {{ .Values.service.protocol }}
    port: {{ .Values.service.portExpose }}
    targetPort: {{ .Values.service.portTarget }}
