apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app1
  labels:
    app: web-app1
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app1
  template:
    metadata:
      labels:
        app: web-app1
    spec:
      containers:
      - name: app1
        image: {{ .Values.image.name }}
        ports:
        - containerPort: {{ .Values.image.containerPort }}
        resources:
          limits: 
            memory: {{ .Values.resources.memory }}
            cpu: {{ .Values.resources.cpu }}
        env:
          - name: MESSAGE
            value: '{{ .Values.env.valueMessage }}'
          - name: PORT
            value: '{{ .Values.env.valuePort }}'
